import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import modalitiesRouter from "./modalities";
import intakesRouter from "./intakes";
import plansRouter from "./plans";
import providersRouter from "./providers";
import favoritesRouter from "./favorites";
import progressRouter from "./progress";
import adminRouter from "./admin";
import coachRouter from "./coach";
import employersRouter from "./employers";
import lmnRouter from "./lmn";
import insightsRouter from "./insights";
import referralsRouter from "./referrals";
import magicLinksRouter from "./magicLinks";
import commsPrefsRouter from "./commsPrefs";
import notificationLogRouter from "./notificationLog";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(modalitiesRouter);
router.use(intakesRouter);
router.use(plansRouter);
router.use(providersRouter);
router.use(favoritesRouter);
router.use(progressRouter);
router.use(adminRouter);
router.use(coachRouter);
router.use(employersRouter);
router.use(lmnRouter);
router.use(insightsRouter);
router.use(referralsRouter);
router.use(magicLinksRouter);
router.use(commsPrefsRouter);
router.use(notificationLogRouter);

export default router;
