export default function Legal() {
  return (
    <div className="min-h-screen px-6 md:px-12 py-20" style={{ background: "var(--warm-white)" }}>
      <div className="max-w-3xl mx-auto">
        <div className="section-tag">Legal</div>
        <h1 className="mb-8" style={{ fontFamily: "var(--app-font-serif)", fontSize: "clamp(2.2rem,4vw,3.5rem)", fontWeight: 700, color: "var(--navy)", letterSpacing: "-0.02em" }}>
          Platform Disclaimer
        </h1>

        <div className="p-4 rounded-lg mb-8 text-sm leading-relaxed" style={{ background: "#fef2f2", border: "1px solid #fecaca", borderLeft: "4px solid #dc2626", color: "#7f1d1d" }}>
          <strong style={{ color: "#dc2626" }}>Emergency Resources:</strong> If you are experiencing a medical emergency, call <strong>911</strong> immediately. For mental health crisis support, call or text <strong>988</strong>, or text HOME to <strong>741741</strong>. Do not use this platform in an emergency.
        </div>

        <div className="prose max-w-none" style={{ fontFamily: "var(--app-font-sans)" }}>
          {[
            { title: "1. Not Medical Advice", body: "All content on HealthPlanFactory — including AI-generated wellness plans, modality descriptions, provider listings, coaching messages, and any other information — is provided for general informational and educational purposes only. It does not constitute medical advice, medical diagnosis, or medical treatment recommendations of any kind. Do not rely on information from this platform to make medical decisions." },
            { title: "2. No Healthcare Provider Relationship", body: "Your use of HealthPlanFactory does not create a provider-patient relationship, therapist-client relationship, or any other professional healthcare relationship. HealthPlanFactory is not a licensed medical provider, psychologist, therapist, counselor, or any other type of regulated healthcare professional." },
            { title: "3. Consult a Professional", body: "Before beginning any new wellness program, exercise routine, dietary change, supplement regimen, or any other health-related activity, always consult a licensed and qualified healthcare professional who can evaluate your individual situation. This is especially important if you have existing medical conditions, are pregnant, or are taking prescription medications." },
            { title: "4. AI-Generated Content", body: "Wellness plans and coaching messages are generated by artificial intelligence. AI systems can make mistakes. AI-generated content on this platform has not been reviewed or approved by licensed medical professionals. It should not be treated as personalized medical advice." },
            { title: "5. Provider Listings", body: "HealthPlanFactory lists wellness and healthcare providers for informational discovery purposes only. We do not independently verify provider credentials, licenses, insurance status, or qualifications. We do not endorse any listed provider or guarantee the quality, safety, or effectiveness of any service provided by any listed provider. It is your responsibility to verify credentials and make your own informed decisions." },
            { title: "6. HSA/FSA Information", body: "Any information regarding HSA/FSA eligibility for wellness services is general guidance only. The actual eligibility of any specific expense for HSA or FSA reimbursement is determined solely by your plan documents and plan administrator. HealthPlanFactory makes no representations regarding specific tax treatment of any expense. Consult your plan administrator and a qualified tax advisor." },
            { title: "7. Limitation of Liability", body: "To the maximum extent permitted by applicable law, HealthPlanFactory, its officers, directors, employees, and agents shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages arising from your use of this platform, including without limitation, any damages resulting from reliance on content provided by this platform." },
          ].map((section) => (
            <div key={section.title} className="mb-8">
              <h2 className="text-base font-semibold mb-2" style={{ color: "var(--navy)", fontFamily: "var(--app-font-sans)" }}>{section.title}</h2>
              <p className="text-sm font-light leading-relaxed" style={{ color: "var(--text-secondary)" }}>{section.body}</p>
            </div>
          ))}
        </div>

        <p className="text-xs mt-8 pt-4" style={{ color: "var(--text-muted)", borderTop: "1px solid rgba(27,45,79,0.1)" }}>
          Last updated: {new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}
        </p>
      </div>
    </div>
  );
}
